The to be compiled library has to come before the required libs.
Index: codeslayer-2.0.1/codeslayer/Makefile.am
===================================================================
--- codeslayer-2.0.1.orig/codeslayer/Makefile.am	2012-04-01 20:31:23.000000000 +0200
+++ codeslayer-2.0.1/codeslayer/Makefile.am	2012-09-29 15:21:52.920983396 +0200
@@ -118,7 +118,7 @@
 bin_PROGRAMS = codeslayer
 codeslayer_SOURCES = codeslayer-main.c
 codeslayer_CPPFLAGS = -I$(top_srcdir)
-codeslayer_LDADD = $(CODESLAYER_LIBS) libcodeslayer.la
+codeslayer_LDADD = libcodeslayer.la $(CODESLAYER_LIBS)
 
 datadir = @datadir@
 datarootdir= @datarootdir@
Index: codeslayer-2.0.1/codeslayer/Makefile.in
===================================================================
--- codeslayer-2.0.1.orig/codeslayer/Makefile.in	2012-04-11 02:52:53.000000000 +0200
+++ codeslayer-2.0.1/codeslayer/Makefile.in	2012-09-29 15:22:26.068982411 +0200
@@ -452,7 +452,7 @@
 libcodeslayer_la_CPPFLAGS = -I$(top_srcdir)
 codeslayer_SOURCES = codeslayer-main.c
 codeslayer_CPPFLAGS = -I$(top_srcdir)
-codeslayer_LDADD = $(CODESLAYER_LIBS) libcodeslayer.la
+codeslayer_LDADD = libcodeslayer.la $(CODESLAYER_LIBS) 
 all: all-am
 
 .SUFFIXES:
