.TH UGET-GTK "1" "July 2009" "uget-gtk 1.4.9" "User Commands"
.SH NAME
uget-gtk \- a download manager that uses gtk+2, and libcurl
.SH SYNOPSIS
.B uget-gtk
.RI [ options ]
.RI [ URL ]
.SH DESCRIPTION
.SS "Help Options:"
.TP
\fB\-?, \-\-help\fR
Show help options.
.TP
\fB\-\-help\-all\fR
Show all help options.
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.SS "Application Options:"
.TP
\fB\-\-quiet\fR
add download directly. Don't show dialog.
.TP
\fB\-\-category\-index\fR=\fIN\fR
add download to Nth category. (default \fB\-1\fR)
.TP
\fB\-\-folder\fR=\fIFOLDER\fR
placed download file in FOLDER.
.TP
\fB\-\-filename\fR=\fIFILE\fR
set download filename to FILE.
.TP
\fB\-\-user\fR=\fIUSER\fR
set both ftp and http user to USER.
.TP
\fB\-\-password\fR=\fIPASS\fR
set both ftp and http password to PASS.
.TP
\fB\-\-proxy\-type\fR=\fIN\fR
set proxy type to N. (0=Don't use)
.TP
\fB\-\-proxy\-host\fR=\fIHOST\fR
set proxy host to HOST.
.TP
\fB\-\-proxy\-port\fR=\fIPORT\fR
set proxy port to PORT.
.TP
\fB\-\-proxy\-user\fR=\fIUSER\fR
set USER as proxy username.
.TP
\fB\-\-proxy\-password\fR=\fIPASS\fR
set PASS as proxy password.
.TP
\fB\-\-http\-user\fR=\fIUSER\fR
set http user to USER.
.TP
\fB\-\-http\-password\fR=\fIPASS\fR
set http password to PASS.
.TP
\fB\-\-http\-referer\fR=\fIURL\fR
include `Referer: URL' header in HTTP request.
.TP
\fB\-\-http\-cookie\-data\fR=\fISTRING\fR
load cookies from STRING.
.TP
\fB\-\-http\-cookie\-file\fR=\fIFILE\fR
load cookies from FILE.
.TP
\fB\-\-http\-post\-data\fR=\fISTRING\fR
use the POST method; send STRING as the data.
.TP
\fB\-\-http\-post\-file\fR=\fIFILE\fR
use the POST method; send contents of FILE
.TP
\fB\-\-ftp\-user\fR=\fIUSER\fR
set ftp user to USER.
.TP
\fB\-\-ftp\-password\fR=\fIPASS\fR
set ftp password to PASS.
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.SH AUTHOR
\fBuget\fR was written by Raymond Huang <plushuang at users.sourceforge.net>,and this manual page was originally written by Dennis Craven <dcraven@gmail.com>

