# wrong filename of wav files
Index: freefilesync-7.9/Makefile
===================================================================
--- freefilesync-7.9.orig/Makefile	2016-02-13 19:04:01.000000000 +0100
+++ freefilesync-7.9/Makefile	2016-02-13 19:05:00.992508051 +0100
@@ -113,7 +113,9 @@
 	mkdir -p $(APPSHAREDIR)
 	cp -R ../Build/Languages/ \
 	../Build/Help/ \
-	../Build/Sync_Complete.wav \
+	../Build/ding.wav \
+	../Build/gong.wav \
+	../Build/harp.wav \
 	../Build/Resources.zip \
 	../Build/styles.gtk_rc \
 	$(APPSHAREDIR)
