#!/bin/sh

set -e

case "$1" in
    configure|abort-upgrade)
        update-alternatives --install /usr/bin/unrar unrar \
        /usr/bin/unrar-freeware 50 \
        --slave /usr/share/man/man1/unrar.1.gz unrar.1.gz \
        /usr/share/man/man1/unrar-freeware.1.gz
    ;;
    
    abort-remove|abort-deconfigure)
    ;;
    
    *)
      echo "postinst called with unknown argument \$1'" >&2
      exit 0
    ;;
esac

#DEBHELPER#

exit 0
