.TH UNETBOOTIN 1 "November  2, 2008"
.SH NAME
unetbootin \- program to install Linux/BSD distributions to a partition or USB drive
.SH SYNOPSIS
.B unetbootin
.SH DESCRIPTION
This manual page documents briefly the
.B unetbootin
command.
.PP
\fBunetbootin\fP allows for the installation of various Linux/BSD distributions to a partition or USB drive, so it's no different from a standard install, only it doesn't need a CD. It can create a dual-boot install, or replace the existing OS entirely.
.SH AUTHOR
unetbootin was written by Geza Kovacs <geza0kovacs@gmail.com>
.PP
This manual page was written by Eugene V. Lyubimkin <jackyf.devel@gmail.com>,
for the Debian project (but may be used by others).
