#!/bin/bash
ON_USER=$(who | awk '{print $1}' | sed '/^root$/d' | uniq)

case `lsb_release -cs` in
	helena)
		UBUVER="karmic" ;;
	isadora)
		UBUVER="lucid" ;;
	julia)
		UBUVER="maverick" ;;
	katya)
		UBUVER="natty" ;;
	lisa)
		UBUVER="oneiric" ;;
	karmic)
		UBUVER="karmic" ;;
	lucid)
		UBUVER="lucid" ;;
	maverick)
		UBUVER="maverick" ;;
	natty)
		UBUVER="natty" ;;
	oneiric)
		UBUVER="oneiric" ;;
	precise)
		UBUVER="precise" ;;
esac


if [[ ! -e /etc/y-ppa-manager.conf ]]; then

#DOWN_DIR=`cat /home/$ON_USER/.config/user-dirs.dirs | grep XDG_DOWNLOAD_DIR | sed -e 's/XDG_DOWNLOAD_DIR="$HOME\///g' -e 's/"//g'`

	echo "#ppa-purge behavior: auto - don't require any user input; manual - opens a terminal window asking the user how to solve the issue (this is the default behavior). Set manual/auto below:" > /etc/y-ppa-manager.conf
	echo "ppa-purge=manual" >> /etc/y-ppa-manager.conf
	echo $'\n' >> /etc/y-ppa-manager.conf
	echo "#By default, the integrated PPA Search will display packages for your Ubuntu version. However, you can change this below:" >> /etc/y-ppa-manager.conf
	echo "searchdist=$UBUVER" >> /etc/y-ppa-manager.conf
	echo $'\n' >> /etc/y-ppa-manager.conf
	echo "#Use Ubuntu Indicator (default: disabled):" >> /etc/y-ppa-manager.conf
	echo "indicator=disabled" >> /etc/y-ppa-manager.conf
#	echo $'\n' >> /etc/y-ppa-manager.conf
#	echo "#Downloads folder (default: /home/$ON_USER/$DOWN_DIR/y-ppa-manager):" >> /etc/y-ppa-manager.conf
#	echo "downloads=/home/$ON_USER/$DOWN_DIR/y-ppa-manager" >> /etc/y-ppa-manager.conf
	echo $'\n' >> /etc/y-ppa-manager.conf
	echo "rankings=false" >> /etc/y-ppa-manager.conf

#	mkdir -p "/home/$ON_USER/$DOWN_DIR/y-ppa-manager"
#	chown -R "$ON_USER" "/home/$ON_USER/$DOWN_DIR/y-ppa-manager"


else 

	RANKINGS=`grep "rankings=" /etc/y-ppa-manager.conf`
	if [[ ! $RANKINGS ]]; then
		echo $'\n' >> /etc/y-ppa-manager.conf
		echo "rankings=false" >> /etc/y-ppa-manager.conf
	fi

	INDICATOR=`grep "indicator=" /etc/y-ppa-manager.conf`
	if [[ ! $INDICATOR ]]; then
		echo $'\n' >> /etc/y-ppa-manager.conf
		echo "#Use Ubuntu Indicator (default: disabled):" >> /etc/y-ppa-manager.conf
		echo "indicator=disabled" >> /etc/y-ppa-manager.conf
	fi
fi


#DEBHELPER#

exit 0
