.TH GITSO 1 "October 2008" "gitso-0.6" "Gitso"
.SH NAME
gitso - Gitso is to support others
.SH SYNOPSIS
.B gitso
[
.B --dev
|
.B --listen
|
.B --connect
.I host
|
.B --list
.I list
|
.B --version
|
.B --help
]
.SH DESCRIPTION
Gitso is a frontend to reverse VNC connections. It is meant to be a simple two-step process that connects one person to another's screen in the context of giving technical support.
.SH OPTIONS
.TP
.B --dev
Configures paths for running Gitso in the source tree.
.TP
.B --listen
Start Gitso and listen for incoming connections
.TP
.B --connect
Starts gitso and automatically connects to
.I host
which is an IP or domain name (address of support giver).
.TP
.B --list
Alternative support list, where
.I list 
is either a URL of a remote file or path to local file.
.TP
.B --version
The current Gitso version.
.TP
.B --help
Display the help menu.

.SH HOST FILES
.I $HOME/.gitso-hosts
.I /usr/share/gitso/hosts.txt

.SH EXAMPLES
.TP
gitso --list http://support.mydomain.com/techs.txt
Gets the list of technician IP's or DN's from techs.txt
.TP
gitso --list sanda.mydomain.com,aicha.mydomain.com
Adds these three entries to the list of support techs.
.TP
gitso --connect hank.mydomain.com
Automatically connects to hank.mydomain.com

.SH SEE ALSO
.I x11vnc
.I vncviewer

.SH AUTHOR
Aaron Gerber and Derek Buranen
