#!/bin/sh
set -e

# Handle symlink to directory conversion (happened in 2.6.0-1)

HELPDIR=/usr/share/gnome/help/

if [ -L $HELPDIR/gnucash-guide ]; then
    rm $HELPDIR/gnucash-guide
fi
if [ -L $HELPDIR/gnucash-help ]; then
    rm $HELPDIR/gnucash-help
fi

#DEBHELPER#
