#!/bin/sh

LD_LIBRARY_PATH=/usr/lib/xnviewmp:/usr/lib/xnviewmp/lib:/usr/lib/xnviewmp/lib/codecs:/usr/lib/xnviewmp/lib/imageformats:/usr/lib/xnviewmp/lib/phonon_backend:/usr/lib/xnviewmp/Plugins:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
QT_PLUGIN_PATH=/usr/lib/xnviewmp:/usr/lib/xnviewmp/lib:/usr/lib/xnviewmp/lib/codecs:/usr/lib/xnviewmp/lib/imageformats:/usr/lib/xnviewmp/lib/phonon_backend:/usr/lib/xnviewmp/Plugins:$QT_PLUGIN_PATH
export QT_PLUGIN_PATH

/usr/lib/xnviewmp/XnView "$@"
