.TH cvpcb 1 "June 15, 2007" "cvpcb"

.SH NAME
cvpcb \- assign components to a netlist.

.SH DESCRIPTION
.PP
.B cvpcb
allows you to assign each component that appears in the netlist to a component
footprint which will represent it on a PCB and adds this information to the
netlist.

.SH SYNOPSIS
.B cvpcb
.RI [ netlist ]

.SH AUTHOR
Richard Antony Burton <richardaburton@gmail.com>
