.TH eeschema 1 "June 15, 2007" "eeschema"

.SH NAME
eeschema \- a powerful schematic capture application.

.SH DESCRIPTION
.PP
.B eeschema
integrates the functions of drawing, control, layout, library management and 
access to the PCB design software. It also allows hierarchical drawings, using
multi-sheets diagrams. It is intended to work with printed circuit software such
as pcbnew, to which it will provide the netlist file. Eeschema also integrates a
component editor which allows the creation, editing and visualization of
components, as well as the handling of the symbol libraries (import, export,
addition and deletion of library components).

.SH SYNOPSIS
.B eeschema
.RI [ schematic ]

.SH AUTHOR
Richard Antony Burton <richardaburton@gmail.com>
