.TH kicad 1 "June 15, 2007" "kicad"

.SH NAME
kicad \- manager application for Kicad projects.

.SH DESCRIPTION
.PP
The kicad utility program is a project manager that facilitates the use of the
various programs required to draw schematics, lay out PCBs, generate and check
the production files.

.SH SYNOPSIS
.B kicad
.RI [ project ]

.SH AUTHOR
Richard Antony Burton <richardaburton@gmail.com>
