.TH pcbnew 1 "June 15, 2007" "pcbnew"

.SH NAME
pcbnew \- a powerful printed circuit board editor.

.B pcbnew
manages libraries of modules. Each module is a drawing of the physical
component, including its footprint, and the layout of pads providing connections
to the component. The required modules are automatically loaded during the
reading of the netlist produced by pcbnew.

.SH SYNOPSIS
.B pcbnew
.RI [ boardfile ]

.SH AUTHOR
Richard Antony Burton <richardaburton@gmail.com>
