usr/bin
#usr/lib/udev lib/ # udev rules are useless right now
usr/lib/calibre/calibre/
usr/lib/calibre/odf
usr/lib/calibre/templite
usr/lib/calibre/html5lib
usr/lib/calibre/qtcurve
usr/lib/calibre/six.py
usr/lib/calibre/regex
usr/lib/calibre/tinycss
usr/share/
../local/*.desktop usr/share/applications
../local/mime/*.xml usr/share/mime/packages/
usr/share/bash-completion/completions/calibre etc/bash_completion.d
