#!/bin/bash

# This script will run on any debian base ...
# Assuming that packages are already installed.

#Using source in the share folder from the debian package
cd /usr/share/webcamstudio/vloopback-src
mkdir /tmp/webcamstudio-vloopback-src
cp * /tmp/webcamstudio-vloopback-src
cd /tmp/webcamstudio-vloopback-src

# Compiling the source code
zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --title "VLoopback Installer" \
	--question --text="Will now compile source code."
if [ $? != "0" ]; then
	exit;
fi
gksudo make | zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --progress --auto-close --pulsate --title "VLoopback Installer" --text="Compiling..."
RESULT=$?
if [ $RESULT != "0" ]; then
    zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --title "VLoopback Installer" \
	--error --text="An error occured when compiling source code..."
    exit;
fi

# if everything when well, we install the module
zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --title "VLoopback Installer" \
	--question --text="Will now install new module vloopback into your system."
if [ $? != "0" ]; then
	exit;
fi
gksudo make install | zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --progress --auto-close --pulsate --title "VLoopback Installer" --text="Installing..."
RESULT=$?
if [ $RESULT != "0" ]; then
    zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --title "VLoopback Installer" \
	--error --text="An error occured when installing module..."
    exit;
fi

# Ok, modules is not in place
# Now setting the module to auto-load on boot
grep vloopback /etc/modules  | zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --progress --auto-close --pulsate --title "VLoopback Installer" --text="Auto-Loading..."
RESULT=$?
if [ $RESULT != "0" ]; then
    zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --title "VLoopback Installer" \
	--question --text="Will now Install module vloopback to auto-load on the start-up."
	if [ $? != "0" ]; then
		exit;
	fi
    gksudo bash -c "echo #WebcamStudio virtual webcam  >> /etc/modules" | zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --progress --auto-close --pulsate --title "VLoopback Installer" --text="Auto-Loading..."
    gksudo bash -c "echo vloopback >> /etc/modules" | zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --progress --auto-close --pulsate --title "VLoopback Installer" --text="Auto-Loading..."
    RESULT=$?
    if [ $RESULT != "0" ]; then
	zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --title "VLoopback Installer" \
	--error --text="An error occured when adding module vloopback to auto-load on boot..."
        exit;
    
    fi
else
    zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --title "VLoopback Installer" \
	--question --text="Module vloopback already installed to auto-load."
	if [ $? != "0" ]; then
		exit;
	fi
fi

# loading the module for instant use

lsmod | grep vloopback  | zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --progress --auto-close --pulsate --title "VLoopback Installer" --text="Unloading..."
RESULT=$?
if [ $RESULT == "0" ]; then
    zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --title "VLoopback Installer" \
	--question --text="Will now unload current vloopback from memory."
	if [ $? != "0" ]; then
		exit;
	fi

    gksudo rmmod vloopback  | zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --progress --auto-close --pulsate --title "VLoopback Installer" --text="Unloading..."
    RESULT=$?
    if [ $RESULT != "0" ]; then
	zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --title "VLoopback Installer" \
	--error --text="An error occured when unloading  module vloopback..."
	exit;
    fi
fi

zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --title "VLoopback Installer" \
	--question --text="Will now load module vloopback in memory"
if [ $? != "0" ]; then
	exit;
fi
gksudo modprobe vloopback  | zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --progress --auto-close --pulsate --title "VLoopback Installer" --text="Loading..."
RESULT=$?
if [ $RESULT != "0" ]; then
    zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --title "VLoopback Installer" \
	--error --text="An error occured when loading module vloopback..."
    exit;
fi

# Clean-up of compiled binaries...
gksudo make clean | zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --progress --auto-close --pulsate --title "VLoopback Installer" --text="Cleaning..."

# Now it should work
zenity --window-icon=/usr/share/pixmaps/webcamstudio.png --title "VLoopback Installer" \
	--info --text="Module vloopback is now installed and ready to use..."

gksudo "chmod 666 /dev/video*"
gksudo "rm -R /tmp/webcamstudio-vloopback-src"

