#!/bin/bash
# WebcamStudio for GNU/Linux Launcher
# Patrick Balleux 2009
# Version 0.54
INSTALLDIR=/usr/lib/webcamstudio
JAVA_DIR=/usr/lib/jvm/java-6-openjdk/bin
if [ -f $JAVA_DIR/java ]
then
    JAVA_DIR=/usr/lib/jvm/java-6-openjdk/bin
else
    JAVA_DIR=/usr/lib/jvm/java-6-sun/bin
fi
echo "Using JRE: $JAVA_DIR"

PADSP=
if [ -f /usr/bin/padsp ] 
then
	PADSP="/usr/bin/padsp"
else
	PADSP=""
fi
if [ -e /dev/raw1394 ] 
then
	if [ ! -w /dev/raw1394 ]
	then
		gksudo --description "You have a Firewire device available but it is not readable.  Enter you password to make it readable." chmod 444 /dev/raw1394
	fi
fi
$PADSP $JAVA_DIR/java -jar $INSTALLDIR/WebcamStudio.jar

