Index: upp-0.0r1659/uppsrc/Makefile
===================================================================
--- upp-0.0r1659.orig/uppsrc/Makefile	2009-10-30 01:56:32.147681718 +0100
+++ upp-0.0r1659/uppsrc/Makefile	2009-10-30 01:58:44.375183468 +0100
@@ -211,7 +211,7 @@
 	$(OutDir_RichText)RichText.a \
 	$(OutDir_plugin_png)pngreg.o \
 	$(OutDir_plugin_png)png.a
-	c++ -o $(OutFile) -Wl,-s $(LIBPATH) -Wl,-O,2 $(LINKOPTIONS) \
+	c++ -o $(OutFile) -Wl,-s,--as-needed $(LIBPATH) -Wl,-O,2 $(LINKOPTIONS) \
 		$(OutDir_ide)SelectPkg.o \
 		$(OutDir_ide)UppWspc.o \
 		$(OutDir_ide)UppDlg.o \
Index: upp-0.0r1659/domake
===================================================================
--- upp-0.0r1659.orig/domake	2009-10-30 02:16:45.255206135 +0100
+++ upp-0.0r1659/domake	2009-10-30 02:16:57.495207874 +0100
@@ -14,4 +14,3 @@
 	make -C uppsrc
 fi
 
-cp uppsrc/ide.out ~/theide
