.\" Author: Jose Luis Tallon <jltallon@adv-solutions.net>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with the Debian GNU/Linux system; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
.\" 02111-1307 USA
.TH kchmviwer "1" "December 2005"
.SH NAME
kchmviewer \- Windows CHM viewer for KDE
.SH SYNOPSIS
kchmviewer
.SH DESCRIPTION
.B kchmviewer
makes it possible to browse native Windows CHM files under KDE.
.PP
Complete documentation can be found in docbook format in
/usr/share/doc/kde/HTML/<lang>/kchmviewer/ on this system.
.SH AUTHOR
 George Yunaev <gyunaev@ulduzsoft.com>
.PP
This manual page was written by Jose Luis Tallon 
.nh
<jltallon@adv\-solutions.net> 
for the \fBDebian\fP system (but may be used by others).
