.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH OGMRIP 1 "July 16, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
ogmrip \- An application to rip and encode DVD for GNOME
.SH SYNOPSIS
.B ogmrip
OGMRip is an application and a set of libraries for ripping and encoding DVDinto AVI, OGM, MP4, or Matroska files  using a wide variety of codecs. It relies on mplayer, mencoder, ogmtools, mkvtoolnix, oggenc, lame, and faac to perform its tasks.
.SH DESCRIPTION
\fBogmrip\fP is an application and a set of libraries for ripping and encoding DVDinto AVI, OGM, MP4, or Matroska files  using a wide variety of codecs. It relies on mplayer, mencoder, ogmtools, mkvtoolnix, oggenc, lame, and faac to perform its tasks.
Features :
.TP
 transcodes from DVD or files
.TP
 outputs OGM, AVI, MP4, or Matroska files
.TP
 supports a lot of codecs (Vorbis, MP3, PCM, AC3, DTS, AAC, XviD, LAVC, X264, Theora)
.TP
 calculates video bitrate for a given file size
.TP
 autodetects cropping parameters and scaling factors
.TP
 supports multiple audio and subtitles streams encoding
.TP
 extracts subtitles in SRT or VobSub format
.TP
 uses maximum quality codecs switches
.TP
 rips contiguous chapters
.TP
 supports external audio (PCM, MP3, AC3, DTS, AAC, Vorbis)
.TP
 and subtitle (MicroDVD, SubRip, SRT, Sami, VPlayer, RT, SSA, PJS, MPSub, AQT, JacoSub, VobSub) files

Complet user manuel available on the website of ogmrip : http://ogmrip.sourceforge.net/en/manual.html

.SH AUTHOR
ogmrip was written by Olivier Rolland <billl@users.sf.net>
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
