.\" This manpage is copyright (C) 2005-2009 Christine Spang.
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with the Debian GNU/Linux system; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
.\" 02111-1307 USA
.\"
.TH nautilus-actions-schemas 1 "2009-08-06" "Debian GNU/Linux"
.SH NAME
nautilus-actions-schemas \- Deprecated for now

That program is not available as GConf2 is to be deprecated.
It may come back when nautilus-actions will use gsettings.

.SH SEE ALSO
.IR nautilus(1), nautilus-actions(1), nautilus-actions-new(1),
    nautilus-actions-run(1), nautilus-actions-print(1)
