.\" This manpage is copyright (C) 2011 Jean Schurger and Alice Ferrazzi.
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with the Debian GNU/Linux system; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
.\" 02111-1307 USA
.\"
.TH nautilus-actions-print 1 "2011-05-11" "Debian GNU/Linux"
.SH NAME
nautilus-actions-print \- Print a menu or an action to stdout.
.SH SYNOPSIS
nautilus-actions-print [OPTION]
.SH OPTIONS
.SS Help Options
.TP
\-?, \fB\-\-help\fR
Show help options
.TP
\-?, \fB\-\-help\-all\fR
Show all help options
.TP
\-?, \fB\-\-help\-misc\fR
Miscellaneous options
.SS Miscellaneous Options
.TP
\-?, \fB\-\-version\fR
Output the version number
.SS Application Options
.TP
\fB\-i\fR, \fB\-\-id=ID\fR
The identifiant ID of the menu or the action to be printed\fR
.TP
\fB\-f\fR, \fB\-\-format=FORMAT\fR
An export FORMAT  [Desktop1]\fR

.SH BUGS
Please report bugs in
.B nautilus-actions
to <submit@bugs.debian.org>. The current bug list may be viewed at
<http://bugs.debian.org/nautilus-actions>.
.SH AUTHOR
.B nautilus-actions
was written by Rodrigo Moya <rodrigo@novell.com>, Frederic Ruaudel
<grumz@grumz.net>, Pierre Wieser <pwieser@trychlos.org>, and contributors.
.PP
This manual page was written by Alice Ferrazzi <aliceinwire@gnumerica.org> and Jean Schurger <jean@schurger.org>, inspired by Christine Spang <christine@debian.org>,
for the Debian project (but may be used by others).
.SH LICENSING
Both the
.B nautilus-actions
source code and this man page are licensed under the GNU General Public
License.
.SH SEE ALSO
.IR nautilus(1), nautilus-actions(1), nautilus-actions-schemas(1),
    nautilus-actions-new(1), nautilus-actions-run(1)

