.\" This manpage is copyright (C) 2009 Christine Spang.
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with the Debian GNU/Linux system; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
.\" 02111-1307 USA
.\"
.TH nautilus-actions-new 1 "2009-08-06" "Debian GNU/Linux"
.SH NAME
nautilus-actions-new \- create new nautilus actions

.SH SYNOPSIS
nautilus-actions-new [OPTION]

.SH DESCRIPTION
.B nautilus-actions-new
creates new actions for the
.B nautilus
file manager non-interactively via the commandline. Action attributes
are specified via command-line options.
.PP
By default, actions are written to STDOUT. However, they can also
be written to a file suitable for later import via
.B nautilus-actions-config-tool
or you can even write the action directory to your GConf configuration
for
.B nautilus-actions

.SH OPTIONS
.SS Help options
\-?, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-output\fR
Choose where the program creates the action

.SS Action-creation options
\fB\-l\fR, \fB\-\-label\fR=\fILABEL\fR
The label of the menu item (mandatory)
.TP
\fB\-t\fR, \fB\-\-tooltip\fR=\fITOOLTIP\fR
The tooltip of the menu item
.TP
\fB\-i\fR, \fB\-\-icon\fR=\fIICON\fR
The icon of the menu item (filename or GTK stock ID)
.TP
\fB\-c\fR, \fB\-\-command\fR=\fIPATH\fR
The path of the command
.TP
\fB\-p\fR, \fB\-\-parameters\fR=\fIPARAMS\fR
The parameters of the command
.TP
\fB\-m\fR, \fB\-\-match\fR=\fIEXPR\fR
A pattern to match selected files against. May include wildcards (* or ?) (you must set one option for each pattern you need)
.TP
\fB\-C\fR, \fB\-\-match\-case\fR=\fIPATH\fR
The path of the command
.TP
\fB\-T\fR, \fB\-\-mimetypes\fR=\fIEXPR\fR
A pattern to match selected files' mimetype against. May include wildcards (* or ?) (you must set one option for each pattern you need)
.TP
\fB\-f\fR, \fB\-\-accept\-files\fR
Set it if the selection must only contain files
.TP
\fB\-d\fR, \fB\-\-accept\-dirs\fR
Set it if the selection must only contain folders. Specify both '\-\-isfile' and '\-\-isdir' options is selection can contain both types of items
.TP
\fB\-M\fR, \fB\-\-accept\-multiple\-files\fR
Set it if the selection can have several items
.TP
\fB\-s\fR, \fB\-\-scheme\fR=\fISCHEME\fR
A valid GVFS scheme where the selected files should be located (you must set one option for each scheme you need)
.PP
.SH BUGS
Please report bugs in
.B nautilus-actions
to <submit@bugs.debian.org>. The current bug list may be viewed at
<http://bugs.debian.org/nautilus-actions>.
.SH AUTHOR
.B nautilus-actions
was written by Rodrigo Moya <rodrigo@novell.com>, Frederic Ruaudel
<grumz@grumz.net>, Pierre Wieser <pwieser@trychlos.org>, and contributors.
.PP
This manual page was written by Christine Spang <christine@debian.org>,
for the Debian project (but may be used by others).
.SH LICENSING
Both the
.B nautilus-actions
source code and this man page are licensed under the GNU General Public
License.
.SH SEE ALSO
.IR nautilus(1), nautilus-actions(1), nautilus-actions-schemas(1),
    nautilus-actions-run(1) nautilus-actions-print(1)
