.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH UMLET 1 "March  11, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
umlet \- simple, text driven UML drawing tool
.SH SYNOPSIS
.B umlet
.RI [ options ] " files" ...
.br
.SH DESCRIPTION
This manual page documents briefly the
.B umlet
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBUMLet\fP is a UML tool aimed at providing a fast way of drawing 
UML diagrams. UML elements are modified using text input instead 
of pop-up dialogs. Elements can be modified and used as 
templates; this way, users can easily tailor UMLet to their 
modeling needs. UMLet supports a variety of UML diagram types: 
class diagrams, use case diagrams, sequence diagrams, state 
diagrams, deployment diagrams, activity diagrams, etc.
.PP
UMLet can only be used for drawing UML diagrams. It does not
support code export nor the XMI format. UMLet allows one to export
diagrams as images or PDF.
.SH AUTHOR
UMLet was written by M. Auer, T. Tschurtschenthaler and L. Meyer.
.PP
This manual page was written by Benjamin Mesing <bensmail@gmx.net>,
for the Debian project (but may be used by others).
