.TH bleachbit 1 2011-07-02 "bleachbit"
.SH NAME
bleachbit \- Delete unnecessary files from the system
.SH SYNOPSIS
.B bleachbit\fR
.TP
.B bleachbit\fR [\fIoptions\fR] cleaner.option1 [cleaner.option2 ...]
.SH DESCRIPTION
BleachBit deletes unnecessary files to free valuable disk space,
maintain privacy, and remove junk. Rid your system of old clutter
including cache, temporary files, cookies, and broken shortcuts.
It wipes clean Bash, Beagle, Epiphany, Firefox, Flash, Java, KDE,
OpenOffice.org, Opera, RealPlayer, rpmbuild, VIM, XChat, and more.
.PP
This is the command line interface for BleachBit.
.SH OPTIONS
.TP
.B -l, --list-cleaners\fR\t list cleaners
.TP
.B -p, --preview\fR\t\t preview files to be deleted and other changes
.TP
.B -d, --delete\fR\t\t delete files and make other permanent changes
.TP
.B -o, --overwrite\fR\t overwrite files to hide contents
.TP
.B --preset\fR\t use options set in the graphical interface
.TP
.B --sysinfo\fR\t show system information
.TP
.B -h, --help\fR\t\t show this help message and exit
.TP
.B -v, --version\fR\t\t output version information and exit
.SH COPYRIGHT
This manual page is Copyright © 2009-2011 Luca Falavigna <dktrkranz@debian.org>.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License, Version 3 or any later
version published by the Free Software Foundation.
